apiVersion: v1
kind: ServiceAccount
metadata:
  name: nutanixabs-provisioner
  
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nutanixabs-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create",  "update", "delete"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: run-nutanixabs-provisioner
subjects:
  - kind: ServiceAccount
    name: nutanixabs-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: nutanixabs-provisioner-runner
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nutanixabs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nutanixabs-provisioner
    spec:
      serviceAccount: nutanixabs-provisioner
      hostNetwork: true
      containers:
        -
          image: "ntnx/nutanixabs-provisioner:1.0"
          name: nutanixabs-provisioner
          args: ["--v=4"]


---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: silver
provisioner: nutanix/abs
parameters:
     prismEndPoint: PRISM_ELEMENT_VIP:9440
     dataServiceEndPoint: DATA_SVC_IP:3260
     user: admin
     password: PE_ADMIN_PASSWD
     secretName: nutanix-abs-secret
     storageContainer: PE_STORAGE_CONTAINER_NAME
     fsType: ext4
     chapAuthEnabled: “false”
#     iscsiSecretName: iscsi_secret_name
     defaultIqn: iqn.1994-05.com.nutanix:k8s-worker

---

apiVersion: v1
kind: Secret
metadata:
  name: nutanix-abs-secret
  namespace: default
data:
  # base64 encoded admin:password. E.g.: echo -n "admin_name:password" | base64
  key: YWRtaW46U1JFczRldmEh
type: nutanix/abs

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: silver-claim
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 3Gi
    storageClassName: silver


